server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    mongodb:
      #106.55.18.86
      host: 106.55.18.86
      username: "admin"
      password: "1353663350"
      port: 27017
      authentication-database: admin
      database: dormitory
      auto-index-creation: true

  redis:
    # 106.55.18.86
    host: 106.55.18.86
    # 63790
    port: 63790
    password: "123456"
    database: 4
    timeout: 5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    空值不返回
    default-property-inclusion: non_null
    time-zone: GMT+8


