server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    mongodb:
      #106.55.18.86
      host: 192.168.128.130
      username: "dorm"
      password: "1353663350"
      # 27017 mongo
      # 27020 mongo分片分区副本集
      port: 27020
      authentication-database: admin
      database: dormitory
      auto-index-creation: true

  redis:
    # 106.55.18.86
    host: 192.168.128.130
    # 63790
    port: 6379
    password: "123456"
    database: 4
    timeout: 5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #    空值不返回
    default-property-inclusion: non_null
    time-zone: GMT+8