server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    mongodb:
      host: 192.168.128.130
      username: "admin"
      password: "1353663350"
      port: 27017
      authentication-database: admin
      database: dormitory

